version: '3'

services:
  hogehoge.localhost:                     #subdomain
    image: vogaro:php7.2
    container_name: hogehoge.localhost    #subdomain
    hostname: hogehoge.localhost          #subdomain
    environment:
     # nginx-proxy
      VIRTUAL_HOST: hogehoge.localhost    #subdomain
    volumes:
      - ./dist:/var/www/html
    ports:
      - 80
    expose:
      - 80
    networks:
      - front

networks:
  front:
    external: true
